{% set name = "jupyterlab-spellchecker" %}
{% set version = "0.8.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 17936d8d8fa8f20cea2c24b2c44cca81061bfd2da94a38b4dcebdfa7972b8859

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version
    - hatch-jupyter-builder >=0.5
    - python-build
    - pip
    - python >=3.8
  run:
    - jupyterlab ~=4.0
    - python >=3.8

test:
  imports:
    - jupyterlab_spellchecker
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - cat labextensions | grep "@jupyterlab-contrib/spellchecker.*OK"  # [unix]
  requires:
    - pip

about:
  home: https://github.com/jupyterlab-contrib/spellchecker
  summary: A spell checker for JupyterLab.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - krassowski
